### Register
POST http://127.0.0.1:8080/api/signup HTTP/1.1
Content-Type: application/json

{ "user": {
    "name": "Jakob",
    "username": "admin",
    "password": "password",
    "email": "admin@site.com"
  }
}

### Login
POST http://127.0.0.1:8080/api/login HTTP/1.1
Content-Type: application/json

{
  "username": "sarah",
  "password": "qwerty123"
}

### Logout
POST http://127.0.0.1:8080/api/logout HTTP/1.1
Content-Type: application/json

{
  "authenticated": "true"
}

### Get users
GET http://127.0.0.1:8080/api/users HTTP/1.1

### Get use by id
GET http://127.0.0.1:8080/api/users/1 HTTP/1.1

### Remove a user
DELETE http://127.0.0.1:8080/api/users/8 HTTP/1.1

### Update a user
PUT http://127.0.0.1:8080/api/users/1 HTTP/1.1
Content-Type: application/json

{

}


